spring:
  application:
    name: order-service

#  config:
#    import: "optional:configserver:"
#  cloud:
#    config:
#      uri: http://localhost:8888

#welcome: "N T Khoi Local"

eureka:
  client:
    register-with-eureka:
      value: true
    fetch-registry:
      value: true;
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost

resilience4j:
  retry:
    instances:
      basic:
        maxRetryAttemps: 5
        waitDuration: 1s


  ratelimiter:
    instances:

      basic:
        limitForPeriod: 2
        limitRefreshPeriod: 5s
        timeoutDuration: 1s


      timeoutExample:
        limitForPeriod: 1
        limitRefreshPeriod: 3s
        timeoutDuration: 5ms